# Generated by Django 4.1.4 on 2023-02-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affair',
            fields=[
                ('affair_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('eventDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('associate_studentID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('studentName', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('course_code', models.CharField(max_length=3)),
                ('payment_status', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=100)),
                ('eventDate', models.DateField()),
                ('payment_amount', models.CharField(max_length=5)),
                ('paymend_date', models.DateField()),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.student')),
            ],
        ),
    ]
