# Generated by Django 4.1.4 on 2023-02-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Affair',
        ),
        migrations.DeleteModel(
            name='Associate',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
